// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package medical

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookings struct {
	ID       int64              `json:"id"`
	UserID   int64              `json:"user_id"`
	DocID    int64              `json:"doc_id"`
	BookedAt pgtype.Timestamptz `json:"booked_at"`
	Slot     pgtype.Timestamptz `json:"slot"`
}

type Departments struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Doctors struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Dept      int32  `json:"dept"`
	Contact   string `json:"contact"`
	// CHECK (experience > 0)
	Experience int32 `json:"experience"`
	// CHECK (fee > 0)
	Fee       int32              `json:"fee"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	ID        int64              `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Contact   string             `json:"contact"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
